In [1]:
import numpy as np

In [2]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.empty(14)

array([ 0. ,  0.1,  0. , -0.1,  0.8, -0.1,  0.8, -0.3,  1. ,  0. ,  0.8,
        0.3,  0.8,  0.1])

In [4]:
u = np.arange(1,77,3)
u

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76])

In [6]:
zlista = [5,3,7,3,7,48,9,43,78,53,22,46,89,90,77,5]
print(zlista)
print(type(zlista))

[5, 3, 7, 3, 7, 48, 9, 43, 78, 53, 22, 46, 89, 90, 77, 5]
<class 'list'>

In [7]:
2*zlista

[5,
 3,
 7,
 3,
 7,
 48,
 9,
 43,
 78,
 53,
 22,
 46,
 89,
 90,
 77,
 5,
 5,
 3,
 7,
 3,
 7,
 48,
 9,
 43,
 78,
 53,
 22,
 46,
 89,
 90,
 77,
 5]

In [8]:
mlista = np.array(zlista)
print(mlista)
print(type(mlista))

[ 5  3  7  3  7 48  9 43 78 53 22 46 89 90 77  5]
<class 'numpy.ndarray'>

In [9]:
2*mlista

array([ 10,   6,  14,   6,  14,  96,  18,  86, 156, 106,  44,  92, 178,
       180, 154,  10])

In [11]:
k = np.linspace(0,10,num=5)
k

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [12]:
l1 = [2,4,6,8]
l2 = [6,3,89,4]
l3 = [112,86,45,8]

In [16]:
l = l1+l2+l3
l

[2, 4, 6, 8, 6, 3, 89, 4, 112, 86, 45, 8]

In [17]:
nl1 = np.array(l1)
nl2 = np.array(l2)
nl3 = np.array(l3)

In [18]:
nl = nl1+nl2+nl3
nl

array([120,  93, 140,  20])

In [21]:
clist = np.concatenate((nl1,nl2,nl3))
clist

array([  2,   4,   6,   8,   6,   3,  89,   4, 112,  86,  45,   8])

In [22]:
z1 = [[2,4],[8,3]]
nz1 = np.array(z1)

In [23]:
z1

[[2, 4], [8, 3]]

In [24]:
nz1

array([[2, 4],
       [8, 3]])

In [26]:
z1[0][1]

4

In [29]:
nz1[0]

array([2, 4])

In [30]:
nz1[0][1]

np.int64(4)

In [31]:
nz1[0,1]

np.int64(4)

In [32]:
#operacje na macierzach
x = np.array([[1,6],[8,9]])
y = np.array([[2,-6],[-3,17]])

x*y

array([[  2, -36],
       [-24, 153]])

In [35]:
p = np.concatenate((x,y),axis=0)
p

array([[ 1,  6],
       [ 8,  9],
       [ 2, -6],
       [-3, 17]])

In [36]:
p.T

array([[ 1,  8,  2, -3],
       [ 6,  9, -6, 17]])

In [37]:
prosta = np.arange(12)
prosta

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [43]:
fp = prosta.reshape(3,4)
fp

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
fp.shape

(3, 4)

In [48]:
mc = np.array([[2,3],[4,5],[9,9]])
mc.shape

(3, 2)

In [49]:
w1 = mc.reshape(6)
w1

array([2, 3, 4, 5, 9, 9])

In [50]:
w = np.arange(15)
mc = w.reshape(3,5)
mc

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [52]:
mc[:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [58]:
mc[2:]

array([[10, 11, 12, 13, 14]])

In [61]:
start = enumerate(w,1)

In [62]:
for i,v in start:
    print(i,v)

1 0
2 1
3 2
4 3
5 4
6 5
7 6
8 7
9 8
10 9
11 10
12 11
13 12
14 13
15 14

In [55]:
pc = (w>12)
w[pc]

array([13, 14])

In [56]:
vb = w[(w>2)&(w<11)]
vb

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
import pandas as pd

In [64]:
obj = pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [65]:
obj.values

array([ 4,  7, -5,  3])

In [73]:
obj2 = pd.Series([4,7,-5,3,8],index=['d','b','costam','c','h'], name="value",dtype=np.int64)
obj2
obj2

d         4
b         7
costam   -5
c         3
h         8
Name: value, dtype: int64

In [74]:
dataf = {
    'miasto':['Warszawa','Kraków','Wrocław','Poznań'],
    'rok':[1990,2000,2010,2020],
    'populacja':[2.6,0.78,0.6,0.67]
}

frame = pd.DataFrame(dataf)
frame

     miasto   rok  populacja
0  Warszawa  1990       2.60
1    Kraków  2000       0.78
2   Wrocław  2010       0.60
3    Poznań  2020       0.67